<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/19 19:03:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=labs',
  'username' => 'labs',
  'password' => 'labs',
  'name' => 'doctrine',
)),);
