<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TodoType', 'doctrine');

/**
 * BaseTodoType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * 
 * @method string   getName()        Returns the current record's "name" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method TodoType setName()        Sets the current record's "name" value
 * @method TodoType setDescription() Sets the current record's "description" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTodoType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('todo_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}