<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Plateform', 'doctrine');

/**
 * BasePlateform
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $tag
 * @property string $description
 * @property string $constructor
 * @property string $icon_url
 * @property Doctrine_Collection $Game
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getTag()         Returns the current record's "tag" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getConstructor() Returns the current record's "constructor" value
 * @method string              getIconUrl()     Returns the current record's "icon_url" value
 * @method Doctrine_Collection getGame()        Returns the current record's "Game" collection
 * @method Plateform           setName()        Sets the current record's "name" value
 * @method Plateform           setTag()         Sets the current record's "tag" value
 * @method Plateform           setDescription() Sets the current record's "description" value
 * @method Plateform           setConstructor() Sets the current record's "constructor" value
 * @method Plateform           setIconUrl()     Sets the current record's "icon_url" value
 * @method Plateform           setGame()        Sets the current record's "Game" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlateform extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plateform');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('tag', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('constructor', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('icon_url', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'plateform_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'tag',
              2 => 'description',
              3 => 'constructor',
              4 => 'slug',
             ),
             ));
        $this->actAs($i18n0);
    }
}