<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuizRequest', 'doctrine');

/**
 * BaseQuizRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $position
 * @property integer $quiz_id
 * @property Quiz $Quiz
 * @property Doctrine_Collection $QuizAnswer
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getPosition()   Returns the current record's "position" value
 * @method integer             getQuizId()     Returns the current record's "quiz_id" value
 * @method Quiz                getQuiz()       Returns the current record's "Quiz" value
 * @method Doctrine_Collection getQuizAnswer() Returns the current record's "QuizAnswer" collection
 * @method QuizRequest         setName()       Sets the current record's "name" value
 * @method QuizRequest         setPosition()   Sets the current record's "position" value
 * @method QuizRequest         setQuizId()     Sets the current record's "quiz_id" value
 * @method QuizRequest         setQuiz()       Sets the current record's "Quiz" value
 * @method QuizRequest         setQuizAnswer() Sets the current record's "QuizAnswer" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_request');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('position', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('quiz_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id'));

        $this->hasMany('QuizAnswer', array(
             'local' => 'id',
             'foreign' => 'quiz_request_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}