<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ShopPos', 'doctrine');

/**
 * BaseShopPos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $ShopProduct
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getShopProduct() Returns the current record's "ShopProduct" collection
 * @method ShopPos             setName()        Sets the current record's "name" value
 * @method ShopPos             setDescription() Sets the current record's "description" value
 * @method ShopPos             setShopProduct() Sets the current record's "ShopProduct" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopPos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_pos');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopProduct', array(
             'local' => 'id',
             'foreign' => 'shop_pos_id'));
    }
}