<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuizAnswer', 'doctrine');

/**
 * BaseQuizAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $is_valid
 * @property integer $position
 * @property integer $quiz_request_id
 * @property QuizRequest $QuizRequest
 * @property Doctrine_Collection $QuizUser
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method enum                getIsValid()         Returns the current record's "is_valid" value
 * @method integer             getPosition()        Returns the current record's "position" value
 * @method integer             getQuizRequestId()   Returns the current record's "quiz_request_id" value
 * @method QuizRequest         getQuizRequest()     Returns the current record's "QuizRequest" value
 * @method Doctrine_Collection getQuizUser()        Returns the current record's "QuizUser" collection
 * @method QuizAnswer          setName()            Sets the current record's "name" value
 * @method QuizAnswer          setIsValid()         Sets the current record's "is_valid" value
 * @method QuizAnswer          setPosition()        Sets the current record's "position" value
 * @method QuizAnswer          setQuizRequestId()   Sets the current record's "quiz_request_id" value
 * @method QuizAnswer          setQuizRequest()     Sets the current record's "QuizRequest" value
 * @method QuizAnswer          setQuizUser()        Sets the current record's "QuizUser" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_answer');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('is_valid', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'no',
              1 => 'yes',
             ),
             'default' => 'no',
             ));
        $this->hasColumn('position', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('quiz_request_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QuizRequest', array(
             'local' => 'quiz_request_id',
             'foreign' => 'id'));

        $this->hasMany('QuizUser', array(
             'local' => 'id',
             'foreign' => 'quiz_answer_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}