<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuizUser', 'doctrine');

/**
 * BaseQuizUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quiz_answer_id
 * @property integer $sf_guard_user_id
 * @property QuizAnswer $QuizAnswer
 * 
 * @method integer    getQuizAnswerId()     Returns the current record's "quiz_answer_id" value
 * @method integer    getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method QuizAnswer getQuizAnswer()       Returns the current record's "QuizAnswer" value
 * @method QuizUser   setQuizAnswerId()     Sets the current record's "quiz_answer_id" value
 * @method QuizUser   setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method QuizUser   setQuizAnswer()       Sets the current record's "QuizAnswer" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_user');
        $this->hasColumn('quiz_answer_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QuizAnswer', array(
             'local' => 'quiz_answer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}