<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TodoGroupPermission', 'doctrine');

/**
 * BaseTodoGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $todo_group_id
 * @property integer $sf_guard_permission_id
 * @property TodoGroup $TodoGroup
 * 
 * @method integer             getTodoGroupId()            Returns the current record's "todo_group_id" value
 * @method integer             getSfGuardPermissionId()    Returns the current record's "sf_guard_permission_id" value
 * @method TodoGroup           getTodoGroup()              Returns the current record's "TodoGroup" value
 * @method TodoGroupPermission setTodoGroupId()            Sets the current record's "todo_group_id" value
 * @method TodoGroupPermission setSfGuardPermissionId()    Sets the current record's "sf_guard_permission_id" value
 * @method TodoGroupPermission setTodoGroup()              Sets the current record's "TodoGroup" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTodoGroupPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('todo_group_permission');
        $this->hasColumn('todo_group_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('sf_guard_permission_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TodoGroup', array(
             'local' => 'todo_group_id',
             'foreign' => 'id'));
    }
}