<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ShopProduct', 'doctrine');

/**
 * BaseShopProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $quantity
 * @property integer $sold
 * @property float $price
 * @property integer $shop_pos_id
 * @property ShopPos $ShopPos
 * @property Doctrine_Collection $ShopHistory
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getQuantity()    Returns the current record's "quantity" value
 * @method integer             getSold()        Returns the current record's "sold" value
 * @method float               getPrice()       Returns the current record's "price" value
 * @method integer             getShopPosId()   Returns the current record's "shop_pos_id" value
 * @method ShopPos             getShopPos()     Returns the current record's "ShopPos" value
 * @method Doctrine_Collection getShopHistory() Returns the current record's "ShopHistory" collection
 * @method ShopProduct         setName()        Sets the current record's "name" value
 * @method ShopProduct         setDescription() Sets the current record's "description" value
 * @method ShopProduct         setQuantity()    Sets the current record's "quantity" value
 * @method ShopProduct         setSold()        Sets the current record's "sold" value
 * @method ShopProduct         setPrice()       Sets the current record's "price" value
 * @method ShopProduct         setShopPosId()   Sets the current record's "shop_pos_id" value
 * @method ShopProduct         setShopPos()     Sets the current record's "ShopPos" value
 * @method ShopProduct         setShopHistory() Sets the current record's "ShopHistory" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_product');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('sold', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             'length' => '',
             ));
        $this->hasColumn('shop_pos_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopPos', array(
             'local' => 'shop_pos_id',
             'foreign' => 'id'));

        $this->hasMany('ShopHistory', array(
             'local' => 'id',
             'foreign' => 'shop_product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}