<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GalleryPhoto', 'doctrine');

/**
 * BaseGalleryPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $album_id
 * @property integer $gallery_id
 * @property Gallery $Gallery
 * 
 * @method string       getName()        Returns the current record's "name" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method string       getAlbumId()     Returns the current record's "album_id" value
 * @method integer      getGalleryId()   Returns the current record's "gallery_id" value
 * @method Gallery      getGallery()     Returns the current record's "Gallery" value
 * @method GalleryPhoto setName()        Sets the current record's "name" value
 * @method GalleryPhoto setDescription() Sets the current record's "description" value
 * @method GalleryPhoto setAlbumId()     Sets the current record's "album_id" value
 * @method GalleryPhoto setGalleryId()   Sets the current record's "gallery_id" value
 * @method GalleryPhoto setGallery()     Sets the current record's "Gallery" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGalleryPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery_photo');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('album_id', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('gallery_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}