<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Game', 'doctrine');

/**
 * BaseGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $year
 * @property integer $editor_id
 * @property integer $game_type_id
 * @property integer $plateform_id
 * @property string $image_url
 * @property string $icon_url
 * @property Editor $Editor
 * @property GameType $GameType
 * @property Plateform $Plateform
 * 
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getDescription()  Returns the current record's "description" value
 * @method integer   getYear()         Returns the current record's "year" value
 * @method integer   getEditorId()     Returns the current record's "editor_id" value
 * @method integer   getGameTypeId()   Returns the current record's "game_type_id" value
 * @method integer   getPlateformId()  Returns the current record's "plateform_id" value
 * @method string    getImageUrl()     Returns the current record's "image_url" value
 * @method string    getIconUrl()      Returns the current record's "icon_url" value
 * @method Editor    getEditor()       Returns the current record's "Editor" value
 * @method GameType  getGameType()     Returns the current record's "GameType" value
 * @method Plateform getPlateform()    Returns the current record's "Plateform" value
 * @method Game      setName()         Sets the current record's "name" value
 * @method Game      setDescription()  Sets the current record's "description" value
 * @method Game      setYear()         Sets the current record's "year" value
 * @method Game      setEditorId()     Sets the current record's "editor_id" value
 * @method Game      setGameTypeId()   Sets the current record's "game_type_id" value
 * @method Game      setPlateformId()  Sets the current record's "plateform_id" value
 * @method Game      setImageUrl()     Sets the current record's "image_url" value
 * @method Game      setIconUrl()      Sets the current record's "icon_url" value
 * @method Game      setEditor()       Sets the current record's "Editor" value
 * @method Game      setGameType()     Sets the current record's "GameType" value
 * @method Game      setPlateform()    Sets the current record's "Plateform" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('editor_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('game_type_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('plateform_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('image_url', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('icon_url', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Editor', array(
             'local' => 'editor_id',
             'foreign' => 'id'));

        $this->hasOne('GameType', array(
             'local' => 'game_type_id',
             'foreign' => 'id'));

        $this->hasOne('Plateform', array(
             'local' => 'plateform_id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $this->actAs($i18n0);
    }
}