<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Editor', 'doctrine');

/**
 * BaseEditor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $website
 * @property string $logo_url
 * @property Doctrine_Collection $Game
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getWebsite()     Returns the current record's "website" value
 * @method string              getLogoUrl()     Returns the current record's "logo_url" value
 * @method Doctrine_Collection getGame()        Returns the current record's "Game" collection
 * @method Editor              setName()        Sets the current record's "name" value
 * @method Editor              setDescription() Sets the current record's "description" value
 * @method Editor              setWebsite()     Sets the current record's "website" value
 * @method Editor              setLogoUrl()     Sets the current record's "logo_url" value
 * @method Editor              setGame()        Sets the current record's "Game" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEditor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('editor');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('website', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('logo_url', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'editor_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
              2 => 'website',
             ),
             ));
        $this->actAs($i18n0);
    }
}