<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Visitor', 'doctrine');

/**
 * BaseVisitor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $birthdate
 * @property integer $department
 * @property integer $event_id
 * @property integer $payment_id
 * @property Event $Event
 * 
 * @method integer getBirthdate()  Returns the current record's "birthdate" value
 * @method integer getDepartment() Returns the current record's "department" value
 * @method integer getEventId()    Returns the current record's "event_id" value
 * @method integer getPaymentId()  Returns the current record's "payment_id" value
 * @method Event   getEvent()      Returns the current record's "Event" value
 * @method Visitor setBirthdate()  Sets the current record's "birthdate" value
 * @method Visitor setDepartment() Sets the current record's "department" value
 * @method Visitor setEventId()    Sets the current record's "event_id" value
 * @method Visitor setPaymentId()  Sets the current record's "payment_id" value
 * @method Visitor setEvent()      Sets the current record's "Event" value
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVisitor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('visitor');
        $this->hasColumn('birthdate', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('department', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('event_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('payment_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}