<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TodoGroup', 'doctrine');

/**
 * BaseTodoGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Todo
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getTodoGroupPermission() Returns the current record's "TodoGroupPermission" collection
 * @method Doctrine_Collection getTodo()                Returns the current record's "Todo" collection
 * @method TodoGroup           setName()                Sets the current record's "name" value
 * @method TodoGroup           setDescription()         Sets the current record's "description" value
 * @method TodoGroup           setTodoGroupPermission() Sets the current record's "TodoGroupPermission" collection
 * @method TodoGroup           setTodo()                Sets the current record's "Todo" collectionGroupPermission
 * @property Doctrine_Collection $Todo
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getTodoGroupPermission() Returns the current record's "TodoGroupPermission" collection
 * @method Doctrine_Collection getTodo()                Returns the current record's "Todo" collection
 * @method TodoGroup           setName()                Sets the current record's "name" value
 * @method TodoGroup           setDescription()         Sets the current record's "description" value
 * @method TodoGroup           setTodoGroupPermission() Sets the current record's "TodoGroupPermission" collection
 * @method TodoGroup           setTodo()                Sets the current record's "Todo" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTodoGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('todo_group');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TodoGroupPermission', array(
             'local' => 'id',
             'foreign' => 'todo_group_permission_id'));

        $this->hasMany('Todo', array(
             'local' => 'id',
             'foreign' => 'todo_group_id'));
    }
}