<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GameType', 'doctrine');

/**
 * BaseGameType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Game
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getGame()        Returns the current record's "Game" collection
 * @method GameType            setName()        Sets the current record's "name" value
 * @method GameType            setDescription() Sets the current record's "description" value
 * @method GameType            setGame()        Sets the current record's "Game" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'game_type_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $this->actAs($i18n0);
    }
}