<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Quiz', 'doctrine');

/**
 * BaseQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $style
 * @property string $background_image
 * @property string $background_color
 * @property enum $is_public
 * @property date $start_at
 * @property date $end_at
 * @property string $image
 * @property string $slug
 * @property Doctrine_Collection $QuizRequest
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method string              getStyle()            Returns the current record's "style" value
 * @method string              getBackgroundImage()  Returns the current record's "background_image" value
 * @method string              getBackgroundColor()  Returns the current record's "background_color" value
 * @method enum                getIsPublic()         Returns the current record's "is_public" value
 * @method date                getStartAt()          Returns the current record's "start_at" value
 * @method date                getEndAt()            Returns the current record's "end_at" value
 * @method string              getImage()            Returns the current record's "image" value
 * @method string              getSlug()             Returns the current record's "slug" value
 * @method Doctrine_Collection getQuizRequest()      Returns the current record's "QuizRequest" collection
 * @method Quiz                setName()             Sets the current record's "name" value
 * @method Quiz                setDescription()      Sets the current record's "description" value
 * @method Quiz                setStyle()            Sets the current record's "style" value
 * @method Quiz                setBackgroundImage()  Sets the current record's "background_image" value
 * @method Quiz                setBackgroundColor()  Sets the current record's "background_color" value
 * @method Quiz                setIsPublic()         Sets the current record's "is_public" value
 * @method Quiz                setStartAt()          Sets the current record's "start_at" value
 * @method Quiz                setEndAt()            Sets the current record's "end_at" value
 * @method Quiz                setImage()            Sets the current record's "image" value
 * @method Quiz                setSlug()             Sets the current record's "slug" value
 * @method Quiz                setQuizRequest()      Sets the current record's "QuizRequest" collection
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay - Futurolan <guillaume@futurolan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('style', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('background_image', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('background_color', 'string', 7, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('is_public', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'no',
              1 => 'yes',
             ),
             ));
        $this->hasColumn('start_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('end_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('image', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('slug', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('QuizRequest', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
              2 => 'background_image',
             ),
             ));
        $this->actAs($i18n0);
    }
}