project:
  connection: doctrine
  tableName: project
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(50)
      notnull: true
    description:
      type: string()
      notnull: false
    repository:
      type: string(250)
      notnull: false
    is_public:
      type: enum
      values: [yes, no]
      default: no
    is_active:
      type: enum
      values: [yes, no]
      default: yes
