<?php

/**
 * EditorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EditorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EditorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Editor');
    }
}