<?php

/**
 * GalleryPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryPhoto');
    }
}