<?php

/**
 * GameTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameType');
    }
}