<?php

/**
 * PageCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageCategory');
    }
}