<?php

/**
 * PlateformTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlateformTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlateformTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plateform');
    }
}