<?php

/**
 * projectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class projectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object projectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('project');
    }
}