<?php

/**
 * QuizRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizRequest');
    }
}