<?php

/**
 * QuizTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quiz');
    }
}