<?php

/**
 * QuizAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizAnswer');
    }
}