<?php

/**
 * QuizUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizUser');
    }
}