<?php

/**
 * ShopProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopProduct');
    }
}