<?php

/**
 * ShopPosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopPosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopPosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopPos');
    }
}