<?php

/**
 * ShopHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopHistory');
    }
}