<?php

/**
 * TodoGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TodoGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TodoGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TodoGroup');
    }
}