<?php

/**
 * TodoGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TodoGroupPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TodoGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TodoGroupPermission');
    }
}