<?php

/**
 * TodoCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TodoCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TodoCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TodoComment');
    }
}