<?php

/**
 * TodoOwnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TodoOwnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TodoOwnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TodoOwner');
    }
}