<?php

/**
 * UserEquipmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserEquipmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserEquipmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserEquipment');
    }
}